<?php

/**
 * @file
 * Primary module hooks for University module.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function university_theme(): array {
  return [
    'university' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for university templates.
 *
 * Default template: university.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the university information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_university(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function university_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish universities.
      $storage = \Drupal::entityTypeManager()->getStorage('university');
      $university_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($university_ids) as $university) {
        $university->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize universities.
      $storage = \Drupal::entityTypeManager()->getStorage('university');
      $university_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($university_ids) as $university) {
        $university->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function university_user_predelete(UserInterface $account): void {
  // Delete universities that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('university');
  $university_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($university_ids)
  );
}
